/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c GeoClue2Manager -p geoclue2manager_p.h:geoclue2manager.cpp org.freedesktop.GeoClue2.xml org.freedesktop.GeoClue2.Manager
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "geoclue2manager_p.h"

/*
 * Implementation of interface class GeoClue2Manager
 */

GeoClue2Manager::GeoClue2Manager(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

GeoClue2Manager::~GeoClue2Manager()
{
}

