/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c GeoClue2Client -p geoclue2client_p.h:geoclue2client.cpp org.freedesktop.GeoClue2.xml org.freedesktop.GeoClue2.Client
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "geoclue2client_p.h"

/*
 * Implementation of interface class GeoClue2Client
 */

GeoClue2Client::GeoClue2Client(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

GeoClue2Client::~GeoClue2Client()
{
}

